### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by BradHeff** [solus-project/3rd-party#377] opened 2018-06-09 01:31 UTC
trying to install flash player for firefox and getting 404 not found error

**Comment by Monsieurzik** [comment] 2018-06-09 21:13
Same issue here. Unable to install it on Solus Plasma

**Comment by yacn** [comment] 2018-06-13 18:03
I think this is a dupe of https://github.com/solus-project/3rd-party/issues/344

**Comment by DataDrake** [comment] 2018-07-14 18:18
Should be fixed now.

**Closed by DataDrake** 2018-07-14 18:18 UTC
